config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]  #do
#    resources :fishes, only: [:index]
#  end
  resources :fishes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:index, :new, :create, :edit, :update]
  end
  resources :bookings, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :fish
  validate :end_at_after_start_at
  validates :start_at, :end_at, presence: true,
    inclusion: { in: (Date.today..Date.today + 1.years) }
  private

  def end_at_after_start_at
    return if end_at.blank? || start_at.blank?

    if end_at < start_at
      errors.add :end_at, "Doit être postérieure à la date de début de réservation"
    end
  end

end

app/models/fish.rb
class Fish < ApplicationRecord
  belongs_to :fish_type
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo, dependent: :destroy
  geocoded_by :address
  validates :name, presence: true
  after_validation :add_city
  after_validation :geocode, if: :will_save_change_to_address?
  # validates :price_per_week, numericality: { only_integer: true }
end

def unavailable_dates
  bookings.pluck(:start_at, :end_at).map do |range|
    { from: range[0], to: range[1] }
  end
end

private

def add_city
  self.city = Geocoder.search(self.address)&.first&.municipality
end

app/models/fish_type.rb
class FishType < ApplicationRecord
  has_many :fishes
  # validates :origin, inclusion: { in: ["Amérique du nord", "Amérique centrale",
  #   "Amérique du sud", "Europe", "Asie", "Afrique"] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
  has_many :fishes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  after_action :verify_authorized, except: :home, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :home, unless: :skip_pundit?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update, :destroy]

  def index
    @fish = Fish.find(params[:fish_id])
    authorize @fish
    puts "@fish.user, current_user #{@fish.user}, #{current_user}"
    if @fish.user == current_user
      @bookings = Booking.where(user: current_user)
    else
      @bookings = Booking.where(user: @fish.user)
     end
  end

  def new
    @fish = Fish.find(params[:fish_id])
    @booking  = Booking.new
    authorize @booking
  end

  def create
    @fish = Fish.find(params[:fish_id])
    @start_at = params[:booking][:start_at]
    @end_at = params[:booking][:end_at]
    @booking = Booking.new(start_at: @start_at, end_at: @end_at, fish: @fish,
      user: current_user, current_cost: @current_cost)
    @booking.current_cost = (@fish.price_per_week * (@booking.end_at - @booking.start_at) / 7).round(0) + 1
    authorize @booking
    if @booking.save
      redirect_to fish_path(@fish, anchor: "booking-#{@booking.id}")
    else
      render :new
    end
  end

  def edit
    @fish = Fish.find(params[:fish_id])
    @statuses = ['En attente', 'Validée', 'Non validée']
    authorize @booking
  end

  def update
    @fish = Fish.find(params[:fish_id])
    @booking.fish = @fish
    authorize @booking
    @booking.update(booking_params)

    redirect_to fish_path(@fish, anchor: "booking-#{@booking.id}")
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to fish_path(@booking.fish)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_at, :end_at, :current_status, :current_cost)
  end

end

app/controllers/fishes_controller.rb
class FishesController < ApplicationController
  before_action :set_fish, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @fishes = Fish.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @fishes = Fish.all
    end
    authorize @fishes
    @markers = @fishes.geocoded.map do |fish|
      {
        lat: fish.latitude,
        lng: fish.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { fish: fish }),
        image_url: helpers.asset_url(
          "https://res.cloudinary.com/drzg8kw0k/image/upload/v1610649377/fishbnb/logo_gbtsbs.png"
        )
      }
    end
  end

  def show
    authorize @fish
  end

  def new
    @fish = Fish.new
    authorize @fish
  end

  def create
    @fish = Fish.new(fish_params)
    authorize @fish
    @fish.user = current_user
    if @fish.valid?
      @fish.save
      redirect_to fish_path(@fish)
    else
      render :new
    end
  end

  def edit
    authorize @fish
  end

  def update
    authorize @fish
    @fish.assign_attributes(fish_params)
    if @fish.valid? 
      @fish.save
      # @fish.photo.attach(params[:photo])
      redirect_to fish_path(@fish)
    else
      render :edit
    end
  end

  def destroy
    authorize @fish
    @fish.destroy
    redirect_to fishes_path
  end

  private

  def set_fish
    @fish = Fish.find(params[:id])
  end

  def fish_params
    params.require(:fish).permit(:name, :price_per_week, :colour, :length,
     :fish_type_id, :available, :photo, :comment, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form-edit.html.erb
<%= simple_form_for [ @fish, @booking ] do |f| %>
  <% if @fish.user == current_user %>
    <p>Date de début de réservation : <strong><%= @booking.start_at %></strong></p>
    <p>Date de fin de réservation : <strong><%= @booking.end_at %></strong></p>
    <p>Vous avez finalisé la réservation avec le statut : <strong><%= @booking.current_status %></p>
  <% else %>
    <%= f.input :start_at, as: :string, label: 'du', placeholder: 'dd/mm/YYYY',
        required: false, input_html: {class: "datepicker"} %>
    <%= f.input :end_at, as: :string, label: 'Au', placeholder: 'dd/mm/YYYY',
        required: false, input_html: {class: "datepicker"} %>
  <% end %>
  <% if @booking.fish.user == current_user && @booking.current_status == 'En attente' %>
    <%= f.input :current_status, collection: @statuses, include_blank: false %>
  <% end %>
  <% if @booking.current_status == 'En attente' %>
    <%= f.submit "Mettre à jour la réservation de #{@fish.name}", class: "btn btn-flat btn-sm" %>
  <% end %>
<% end %>

app/views/bookings/_form-new.html.erb
<%= simple_form_for [ @fish, @booking ] do |f| %>
  <%= f.input :start_at, as: :string, label: 'du', placeholder: 'dd/mm/YYYY',
      required: false, input_html: {class: "datepicker"} %>
  <%= f.input :end_at, as: :string, label: 'Au', placeholder: 'dd/mm/YYYY',
      required: false, input_html: {class: "datepicker"} %>
  <%= f.submit "Réserver #{@fish.name}", class: "btn btn-flat btn-sm" %>
<% end %>

app/views/bookings/_form.html.erb
<%= simple_form_for [ @fish, @booking ] do |f| %>
  <% if@fish.user == current_user %>
    <p><%= @booking.start_at %></p>
    <p><%= @booking.end_at %></p>
  <% else %>
    <%= f.input :start_at, as: :string, label: 'du', placeholder: 'dd/mm/YYYY',
        required: false, input_html: {class: "datepicker"} %>
    <%= f.input :end_at, as: :string, label: 'Au', placeholder: 'dd/mm/YYYY',
        required: false, input_html: {class: "datepicker"} %>
  <% end %>
  <% if @booking.fish.user == current_user && @booking.current_status == 'En attente' %>
    <%= f.input :current_status %>
  <% end %>
  <%= f.submit "Mettre à jour la réservation de #{@fish.name}", class: "btn btn-flat btn-sm" %>
<% end %>

app/views/bookings/edit.html.erb
<h1>Mettre à jour votre demande de réservation de <%= @fish.name %></h1>
<%= render 'form-edit' %>
<%= link_to "Retour à la fiche de #{@fish.name}", fish_path(@fish) %>

app/views/bookings/index.html.erb
<h1>Liste des réservations de <%= @fish.name %> </h1>
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th></th>
      <th>Du</th>
      <th>Au</th>
      <th>Disponibilité</th>
      <th>Tarif de la période</th>
    </tr>
  <thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td>
        </td>
        <td><%= booking.start_at %></td>
        <td><%= booking.end_at %></td>
        <td><%= booking.available %></td>
        <td><%= booking.current_cost %> €</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<h1>Réservation de <%= @fish.name %> par <%= current_user.full_name %></h1>
<%= render 'form-new' %>
<%= link_to "Retour à la fiche de #{@fish.name}", fish_path(@fish), class: 'btn btn-flat btn-sm mt-1' %>

app/views/fishes/_booking_index.html.erb
<% if @fish.user == current_user %>
  <h3 class="mt-3">Les réservations de mon poisson <%= @fish.name %></h3>
<% else %>
  <h3 class="mt-3">Mes réservations de <%= @fish.name %></h3>
<% end %>
<div id="bookings">
  <% if @fish.user == current_user %>
    <% if @fish.bookings.where.not(user: current_user).blank? %>
      <p>Pas de réservation actuellement</p>
    <% else %>
      <table class= "table table-striped table-sm">
        <thead>
          <th>Du</th>
          <th>Au</th>
          <th>Réservé par</th>
          <th>Statut réservation</th>
          <th>Tarif de la période</th>
        </thead>
        <tbody>
          <% @fish.bookings.where.not(user: current_user).each do |booking| %>
            <tr id="booking-<%= booking.id %>">
              <td><%= booking.start_at %></td>
              <td><%= booking.end_at %></td>
              <td><%= booking.user.first_name %></td>
              <td><%= booking.current_status %></td>
              <td><%= booking.current_cost %> €</td>
              <td>
                <ul class="list-inline mb-0">
                  <li class="list-inline-item">
                    <% if policy(booking).update? && booking.current_status == 'En attente' %>
                      <%= link_to edit_fish_booking_path(@fish, booking) do %>
                        <i class="fas fa-edit list-inline-item"></i>
                      <% end %>
                    <% end %>
                  </li>
                  <li class="list-inline-item">
                    <% if policy(booking).destroy? && booking.current_status == 'En attente' %>
                      <%= link_to booking_path(booking), method: :delete, data: {confirm: "Êtes vous sûr ?"} do %>
                        <i class="fas fa-trash-alt list-inline-item"></i>
                      <% end %>
                    <% end %>
                  </li>
                </ul>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  <% else %>
    <% if @fish.bookings.where(user: current_user).blank? %>
      <p>Pas de réservation actuellement</p>
    <% else %>
      <table class= "table table-striped table-sm">
        <thead>
          <th>Du</th>
          <th>Au</th>
          <th>Réservé par</th>
          <th>Statut réservation</th>
          <th>Tarif de la période</th>
        </thead>
        <tbody>
          <% @fish.bookings.where(user: current_user).each do |booking| %>
            <tr id="booking-<%= booking.id %>">
              <td><%= booking.start_at %></td>
              <td><%= booking.end_at %></td>
              <td><%= booking.user.first_name %></td>
              <td><%= booking.current_status %></td>
              <td><%= booking.current_cost %> €</td>
              <td>
                <ul class="list-inline mb-0">
                  <li class="list-inline-item">
                    <% if policy(booking).update? && booking.current_status == 'En attente' %>
                      <%= link_to edit_fish_booking_path(@fish, booking) do %>
                        <i class="fas fa-edit list-inline-item"></i>
                      <% end %>
                    <% end %>
                  </li>
                  <li class="list-inline-item">
                    <% if policy(booking).destroy? && booking.current_status == 'En attente' %>
                      <%= link_to booking_path(booking), method: :delete, data: {confirm: "Êtes vous sûr ?"}, remote: true do %>
                        <i class="fas fa-trash-alt list-inline-item"></i>
                      <% end %>
                    <% end %>
                  </li>
                </ul>
              </td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/fishes/_form.html.erb
<%= simple_form_for @fish, url: fishes_path, method: :post do |f| %>
  <%= f.input :name, label: "Nom", placeholder: "Jean-Jacques" %>
  <%= f.input :price_per_week, label: "Tarif à la semaine en €", placeholder: "15" %>
  <%= f.input :colour, label:"Couleur", placeholder: "Rouge et blanc"%>
  <%= f.input :length, label: "Longueur en cm", placeholder: "35 cm" %>
  <%= f.input :available, label: "Disponible", as: :boolean, input_html: {value: true}  %>
  <%= f.input :address, label: 'Addresse de mise à disposition', placeholder: "16 villa Gaudelet, Paris" %>
  <%= f.input :fish_type_id, label: "Type", label_method: :common_name, collection: FishType.all %>
  <%= f.input :comment, label: "Commentaire", as: :text, placeholder: "Parlez-nous de votre poisson!" %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn btn-flat btn-sm' %>
<% end %>

app/views/fishes/_form_update.html.erb
<%= simple_form_for @fish do |f| %>
  <%= f.input :name, label: "Nom", placeholder: "Jean-Jacques" %>
  <%= f.input :price_per_week, label: "Tarif à la semaine en €", placeholder: "15" %>
  <%= f.input :colour, label:"Couleur", placeholder: "Rouge et blanc"%>
  <%= f.input :length, label: "Longueur en cm", placeholder: "35 cm" %>
  <%= f.input :available, label: "Disponible", as: :boolean, input_html: {value: true}  %>
  <%= f.input :address, label: 'Addresse de mise à disposition', placeholder: "16 villa Gaudelet, Paris" %>
  <%= f.input :fish_type_id, label: "Type", label_method: :common_name, collection: FishType.all %>
  <%= f.input :comment, label: "Commentaire", as: :text, placeholder: "Parlez-nous de votre poisson!" %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn btn-flat btn-sm mb-2' %>
<% end %>

app/views/fishes/_info_window.html.erb
<h2><%= fish.name %></h2>
<p><%= fish.address %></p>

app/views/fishes/edit.html.erb
<h1>Mise à jour de la fiche de <%= @fish.name %></h1>
<%= render "form_update" %>
<%= link_to "Retour à la fiche de #{@fish.name}", fish_path(@fish), class: 'btn btn-flat btn-sm mb-2' %>

app/views/fishes/index.html.erb
<div class="content">
 <% unless @fishes.empty? %>
  <div class="cards-grid">
    <h1> Liste des poissons disponibles à la location</h1>
    <div class="row">
       <% @fishes.each do |fish|%>
        <div class="flex-item card">
          <%= link_to fish_path(fish) do %>
            <div class="card-category" style= "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path fish.photo.attached? ? fish.photo.key : "https://res.cloudinary.com/drzg8kw0k/image/upload/v1611342995/4hux27613gnhmjimg612mls9chi0.jpg" %>')">
              <div class="card-infos">
                <div class="card-name"><%=fish.name %></div>
                <div class="card-price"><%=fish.price_per_week%>€/semaine</div>
                <div class="card-city"><%=fish.city %></div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div id="map" data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>


  <% else %>
  <div>
    <h1> Liste des poissons disponibles à la location</h1>
      <p>Aucun poisson correspondant à votre recherche.</p>
  </div>

  <% end %>


</div>

app/views/fishes/new.html.erb
<h1>Nouveau poisson</h1>
<%= render "form" %>
<%= link_to "retour à la liste de poisson", fishes_path %>

app/views/fishes/show.html.erb
<!-- <h1> Pour en savoir plus sur <%= @fish.name %></h1> -->
<div class="wrapper">

  <div class="one">
    <% if @fish.photo.attached? %>
      <%= image_tag @fish.photo %>
    <% end %>
  </div>

  <div class="two">

    <h1 style="font-size: 30px;"><%= @fish.name %></h1>

    <div class="row-fish" id="specie">
      <p><i class="fas fa-fish" id="specie"></i> <%= @fish.fish_type.common_name %></p>
    </div>

    <div class="row-fish">
      <p id="user"><i class="far fa-id-card"></i> <%= @fish.user.first_name.capitalize %></p>
    </div>

    <div class="row-fish">
      <p id="city"><i class="fas fa-home"></i> <%= @fish.city %></p>
    </div>

    <div class="row-fish" id="available">
      <% if @fish.available %>
        <p>Disponibilitée: <i class="fas fa-check"></i></p>
      <% else %>
       <p>Disponibilitée: <i class="fas fa-times-circle"></i></p>
      <% end %>
    </div>

    <div class="row-fish">
      <p id="color"><i class="fas fa-palette"></i> <%= @fish.colour %></p>
    </div>

    <div class="row-fish">
      <p><i class="fas fa-arrows-alt-h" id="height" style=""></i> <%= @fish.length %>cm</p>
    </div>

    <div class="row-fish">
      <p id="price"><%= @fish.price_per_week %>€/semaine</p>
    </div>

    <div class="row-fish">
      <% if @fish.comment? %>
        <p style="font-size: 20px"> Commentaire <!-- de <%= @fish.user.first_name.capitalize %> --> : </p>
        <p id="description"><%= @fish.comment %></p>
      <% else %>
        <p style="font-size: 20px">Commentaire</p>
        <p> Pas de commentaire de la part du propriétaire </p>
      <% end %>
    </div>

  </div>

  <div class="three">
    <%= render "booking_index" %>
  </div>
</div>

<div class="link">
  <% if @fish.available && @fish.user != current_user %>
    <%= link_to "Réserver #{@fish.name} à la location", new_fish_booking_path(@fish), class: 'btn btn-flat btn-sm' %>
  <% end %>
  <% if policy(@fish).edit? %>
    <%= link_to "Mettre à jour les informations de #{@fish.name}", edit_fish_path(@fish), class: 'btn btn-flat btn-sm' %>
  <% end %>
  <% if policy(@fish).destroy? %>
    <%= link_to "Effacer #{@fish.name}", fish_path(@fish),
    method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-flat btn-sm' %>
  <% end %>
  <%= link_to 'Retour à la liste des poissons', fishes_path, class: 'btn btn-flat btn-sm' %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fishbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <div class="container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="main">
        <%= yield %>
      </div>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/drzg8kw0k/image/upload/v1610648282/fishbnb/shafiqul-islam-9RInlEc0TSA-unsplash_k9frwq.jpg);">
  <div class="container ml-5" style="padding-left:0;">
    <h1 style="font-size: 56px">FISHBNB</h1>
    <p style="font-size: 28px" class="mt-3">Louez les plus beaux poissons rouges</p>
    <a class="btn btn ghost btn-danger mt-3" style='border-radius: 50px' href="fishes#index">Découvrez nos poissons rouges !</a>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by the Bests©
  </div>
</div>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
 <div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/drzg8kw0k/image/upload/v1611012877/fishbnb/logo_gbtsbs_e56ymp.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

<%# https://res.cloudinary.com/drzg8kw0k/image/upload/v1610720267/fishbnb/clown-fish_dvzxof.png %>

    <ul class="navbar-nav mr-auto">
      <li>
        <div class="search-form-control form-group searchbar-index" style="margin: 0px">
          <%= form_tag fishes_path, method: :get, class: 'searchbar-list' do %>
            <%= submit_tag "Recherche", class: "btn btn-ghost btn-sm mr-1" %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control mr-4",
            style: "opacity: 0.4;",
            placeholder: "par nom de poisson" %>
        <% end %>
        </div>
      </li>


      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Proposer votre poisson rouge à la location", new_fish_path, class: "nav-link btn btn-ghost btn-sm ml-2 mr-2" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Nos poissons rouges", fishes_path, class: "nav-link btn btn-ghost btn-sm ml-2 mr-2" %>
        </li>

          <li class="nav-item dropdown ml-2">
            <%= image_tag "https://res.cloudinary.com/drzg8kw0k/image/upload/v1610720267/fishbnb/clown-fish_dvzxof.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <i class="fas fa-caret-down"></i>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
                <%= link_to user_path(current_user), class: "dropdown-item" do %>
                  <i class="fas fa-user"></i> <%= current_user.email %>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                  <i class="fas fa-sign-out-alt"></i> Se déconnecter
                <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>FishBnB : List of Users</h1>
<ul>
  <% @users.each do |user| %>
      <li><%= user.full_name %> (<%= user.email %>)
        <%=  link_to 'see more', user_path(user), class: 'btn btn-flat btn-sm' %>
      </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Detail de l'utilisateur <%= @user.full_name %> </h1>
<p>Nom : <strong><%= @user.last_name %></strong></p>
<p>Prénom : <strong><%= @user.first_name %></strong></p>
<p>address :<strong><%= @user.address %></strong></p>

<p>TODO : rajouter la liste de poissons de l'utilisateur</p>
<%= link_to "Retour à la liste utilisateurs", users_path, class: "btn btn-flat btn-sm" %>